### ISSUE TITLE
How do we test the test environment

### ISSUE THREAD

**Issue by marcric** [marcric/roodle_lms#18]
Prior to our real tests can go on, I suggest the creation of a step by step guide giving the chance for each of the developers test the testing environment locally.

**Comment by marcric** [comment]
I think we should use the User feature and log in, log out and sign in scenarios, to achieve that.

**Comment by kotp** [comment]
I agree.  Working on how to test those.

**Comment by marcric** [comment]
We have agreed on Cucumber and Rspec. And about the others?

Let me show the recent Rails 3 course Alternative:

 group :development, :test do
   gem "rspec", "2.2.0" 
   gem "rspec-rails", "2.2.0" 
   gem 'steak', '1.0.0' 
   gem "ruby-debug"  
 end 
 group :test do 
   gem 'capybara' 
   gem 'database_cleaner' 
   gem 'factory_girl_rails' 
   gem 'launchy', '0.3.7' 
 end 

There are different kinds of tests, and different tools supporting them.

I would like to know more about it before the decision.

We easily agreed on Cucumber and Rspec, but why?

Honestly, I don't know.

**Comment by marcric** [comment]
Another point, sorry for that, but we have the Lessons live where the instructor does everything and we just watch and chat with the class, then we receive that lesson recorded and follow the same steps at home.

Unfortunately I'm two lessons behind the "Tests Lesson". But taking a birds eye on it, I think there is a missing point about configuring the generators.

Take a look here: http://paulbarry.com/articles/2010/01/13/customizing-generators-in-rails-3

But if you decide to use factory-girl gem, instead of fixtures, the ":fixture =>" option should be false!

Regards.

**Comment by kotp** [comment]
Agreed on Cucumber and Rspec, because for one, they are tools that at least have some familiarity.  At least to part of the team.  If there is a comfort level with another tool set, then I am all for that.

The current Gemset, is due to not including 'the kitchen sink' when YAGNI.

The current Gemset does not include factory optionals, outside mocking and stubbing tools, other than what are 'included' in rspec.

launchy was looked at, not going to need it, at least yet.

rspec and rspec-rails was included.

debug, aside from anything 'just there' is not yet added.  Just in the spirit of YAGNI, at least at this point.

**Comment by kotp** [comment]
https://github.com/marcric/roodle_lms/wiki/Testing-the-Application
with a short writeup on how to currently test the testing framework.

No actual tests were written yet.  Still figure that out.

**Comment by marcric** [comment]
OK, I get the test environment working on Windows now.

The spork gem currently doesn't work on Windows, so, I have comment it out from Gemfile.

Will try to understand it and find alternatives.

I get this from spork's github readme file:

RAILS 3

Rails 3.0 support is in progress, but is not ready. The master branch is stable and works with rails 2.3.x.

Rspec 2.x support is not ready either.

If you want to help, see the rails3 branch.

**Comment by kotp** [comment]
It is to speed up the loading of the environment (allows --drb flag to work) to speed up the tests.

Check https://github.com/timcharper/spork/wiki/WindowsSupport to see if that helps.

Normally, rather than removing it, we can conditionally load based on platform.  This would, in this case, mean loading the win32-process gem for windows.  And leaving it out for non-windows systems.  However, from the note above, it isn't so much a windows thing as a Rails 3 thing, and a RSpec2 thing.

**Comment by marcric** [comment]
IMHO, since we have the chance to work on many different environments, we should go for an option that works good on any of them.

Just a thought.

**Comment by kotp** [comment]
True, and this is one of them.  Of course, that depends on if they have updated it to take care of Rspec 2 and Rails 3.

The benefit of using this is limited though, because it will serve us only to the point were we get to about 15 scenarios.  So I don't think it is a strong point, either way, at this point.  Also, we don't have a 'remote' database to contend with.

Close this issue when you are ready.
